### ISSUE TITLE
Go install in stead of go build ?

### ISSUE THREAD

**Issue by brinm00** [ibm-messaging/mq-golang-jms20#21]
Just wondering: shouldn't the "go build" be a "go install" in stead ? Go install places the package (mqjms.a) in $GOPATH/pkg/..../mq-golang-jms20.

**Comment by matrober-uk** [comment]
thanks Melis - I'll update the docs to reflect the scenarios where you would use one option compared to the other.

**Comment by matrober-uk** [comment]
Merged update to the readme to address this question/issue;

> # Check that the source files compile successfully
> cd $GOPATH/src/github.com/ibm-messaging/mq-golang-jms20/mqjms/
> go build
> 
> # If you want to install the compiled module into your path for later use
> # you can do so by running
> go install
