### ISSUE TITLE
can't upgrade to the latest released version

### ISSUE THREAD

**Issue by thekvs** [ibm-messaging/mq-golang-jms20#28]
Hello! 
It seems that `go get github.com/ibm-messaging/mq-golang-jms20` can't upgrade to the latest version `1.3.0` in project's `go.mod` since tag doesn't have required `v` prefix.

**Comment by matrober-uk** [comment]
Hi @thekvs - thanks for spotting that, I've updated the tag to include the "v" prefix - please can you confirm that has resolved the issue you are seeing?

Best regards,

Matt

**Comment by thekvs** [comment]
![image](https://user-images.githubusercontent.com/217860/109132394-d8a41900-7764-11eb-86da-633248e24747.png)
Works now, thanks!

**Comment by matrober-uk** [comment]
great, thanks!  I'll close this issue  👍
