### ISSUE TITLE
How can I activate the option to send asynchronous messages to queue?

### ISSUE THREAD

**Issue by amorfica** [ibm-messaging/mq-golang-jms20#32]
Hi everyone,

I'm now working with GO and I successfully connect to queue and send messages. Right now I'm trying to divide in different goroutines this "send_messages()" function, so I need put messages to the queue asynchronously.

How can I do this?

Thanks

**Comment by matrober-uk** [comment]
Hi @adrian-morfi - welcome!

I'm not sure if you intended to include a link to your specific "send_messages()" function above, or if it was just for illustration purposes?

The recommended approach to be able to send messages from multiple different goroutines is to create a new Context in each goroutine. Each Context you create is a separate connection to the queue manager which means you can write your code to send the messages in each goroutine and it will be handled completely independently from the others.

I hope that helps?

**Comment by amorfica** [comment]
Hi @matrober-uk thanks for your time! 

"send_messages()" function is just for illustration purposes. Your solution is good but I'm looking for solution that is explained in this [documentation](https://www.ibm.com/docs/en/ibm-mq/9.1?topic=application-putting-messages-asynchronously-in-mq-classes-jms). I know that this documentation is for JAVA and I want to know if it is possible using this GO module. 

Regards!

**Comment by matrober-uk** [comment]
Hi @adrian-morfi - ok, thanks - I see what you're looking for.  Is this because you are seeing specific performance problems in the speed of messages being sent, or are you looking to "pre-optimise" your code to go as fast as physically possible?

At the moment this Golang JMS library does not offer support for configuring the asynchronous put option. If you feel comfortable you could submit a PR to introduce that support, or else we could investigate adding this from the IBM side.

**Comment by matrober-uk** [comment]
Notes on potential implementation:
- [JMS externals description](https://www.ibm.com/docs/en/ibm-mq/9.1?topic=application-putting-messages-asynchronously-in-mq-classes-jms) as noted by Adrian
- [Using asynchronous put](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=application-using-asynchronous-put-in-client) which describes using `MQPMO_ASYNC_RESPONSE` on the `MQPMO` object.
  - Setting the MQPMO option is straightforward
  - The more tricky part of the implementation is likely to be `the first error that occurred under an asynchronous call can be determined later through a call to MQSTAT.` in order that errors can be reported at the appropriate interval

**Comment by amorfica** [comment]
Hi @matrober-uk

The logic of the program is easy, for example, you receive 500 records and you must to process them in different goroutines, it is ok, but the bottleneck in this case is that the sendMessage() function of this module need time to send and receive the response, that's the reason I'm looking for a async sendMessage() function in this module. 

I'll looking for the way of the implementation that you proposed and if I got something interesting I'll make PR. 

Thanks again!

**Comment by matrober-uk** [comment]
Hi @adrian-morfi - I've added a branch https://github.com/ibm-messaging/mq-golang-jms20/tree/async-put that contains the first (and most important) part of async put support.

It includes a test case that shows the function in use, in particular;
https://github.com/ibm-messaging/mq-golang-jms20/blob/async-put/asyncput_test.go#L90

The code steps to use it are:
```go
asyncQueue := context.CreateQueue("DEV.QUEUE.1").SetPutAsyncAllowed(jms20subset.Destination_PUT_ASYNC_ALLOWED_ENABLED)
producer := context.CreateProducer().SetDeliveryMode(jms20subset.DeliveryMode_NON_PERSISTENT)

msg := context.CreateTextMessageWithString("message contents")
errSend := producer.Send(syncQueue, msg)
```

Note that the code in that branch **does not** check for any errors when sending the messages - I've tested out the MQSTAT call required to achieve that and I'll add the checking logic in under a separate comment.

In my test scenario it was around 30% quicker to put non-persistent messages with the async put flag enabled than without. There wasn't any observable difference for persistent messages.

Please feel free to check out that branch and give it a try, and I'll follow up with the error handling additions in a few days time.

**Comment by matrober-uk** [comment]
Added a second commit in the branch https://github.com/ibm-messaging/mq-golang-jms20/tree/async-put that allows the user to set the ConnectionFactoryImpl.SendCheckCount in order to trigger an error check to be made every N messages when using async put, for example;
https://github.com/ibm-messaging/mq-golang-jms20/blob/async-put/asyncput_test.go#L195

Code steps:
```go
	// Set the CF flag to enable checking for errors after a certain number of messages
	cf.SendCheckCount = 10

	context, ctxErr := cf.CreateContext()

	// Set up the producer and consumer with the async queue.
	asyncQueue := context.CreateQueue("DEV.QUEUE.1").SetPutAsyncAllowed(jms20subset.Destination_PUT_ASYNC_ALLOWED_ENABLED)
	producer := context.CreateProducer().SetDeliveryMode(jms20subset.DeliveryMode_NON_PERSISTENT)

        // Error check will be made for the first message sent, then for every 10th message after that
        // All other Send calls will return nil error even if there was a problem.
        errSend := producer.Send(asyncQueue, msg)
```

There are a few more tests I want to look at then I'll look to merge this in to the main branch.

**Comment by matrober-uk** [comment]
Support for async put described under this issue has been merged to the master branch under https://github.com/ibm-messaging/mq-golang-jms20/pull/35

(note, I'll be renaming "master" to "main" in the near future in line with latest industry good practice).

**Comment by matrober-uk** [comment]
Closing as implemented - see comments above, or https://github.com/ibm-messaging/mq-golang-jms20/blob/master/asyncput_test.go for examples.
