### ISSUE TITLE
What do you think about use put1 instead of put?

### ISSUE THREAD

**Issue by juancgalvis** [ibm-messaging/mq-golang-jms20#37]
At the moment the JMS 2 golang abstraction makes use of mqput available in MQObject at golang, in Java I have seen that a JMSProducer makes use of mqput1, wich is available in [MQQueueManager.put1](https://github.com/ibm-messaging/mq-golang/blob/64e82e3d0ab71640b224003b918aa02bcfc85b6d/ibmmq/mqi.go#L567) at golang project.

As indicated [here](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=queue-putting-one-message-using-mqput1-call) mqput1 would be cheaper than mqput because there are no an mqopen, mqput and mqclose, these three operations would be a single mqput1.

Would you agree to this change in a pull request?

**Comment by matrober-uk** [comment]
Hi @juancgalvis - welcome!

Switching to PUT1 in the JMSProducer sounds like a good enhancement - I'd be very happy for you to submit a PR to make that change.

Please note the guidelines on [Contributing](https://github.com/ibm-messaging/mq-golang-jms20#contributing), particularly the last sentence about confirming your agreement to the CLA as part of the PR;
> When submitting a pull request, you must include a statement stating you accept the terms in the CLA.

I'll keep an eye out for your update!

**Comment by matrober-uk** [comment]
thanks @juancgalvis for your contribution.  I made a few review comments at https://github.com/ibm-messaging/mq-golang-jms20/pull/38#pullrequestreview-714547785, including the observation that in my test scenario this change **increases the rate of sending messages by 3x, which is fantastic!**
