### ISSUE TITLE
Ability to set custom message header while dispatching message

### ISSUE THREAD

**Issue by ramkumarar** [ibm-messaging/mq-golang-jms20#39]
Iam publishing a message to a Queue and listening via jms listener, I am setting a custom header named event_type which helps on the listener side to select messages based on this type

In java we can setup a custom property as below to setup custom header
message.setStringProperty(JMS_CUSTOM_HEADER_EVENT_TYPE,"some_event_type);

I was looking at the Message interface and I don't see an option to set custom headers while dispatching a message. Can you let me know if this possible? If not can you provide some pointers to extend this library to support this feature
https://github.com/ibm-messaging/mq-golang-jms20/blob/master/jms20subset/Message.go

**Comment by matrober-uk** [comment]
Hi @ramkumarar - currently this Golang JMS client does not have support for setting message properties, although I agree it would be a great feature to add (and is one of the key things called out in the proposed [next-features.txt](https://github.com/ibm-messaging/mq-golang-jms20/blob/master/next-features.txt).

Some notes if you were interested in looking at submitting an implementation;
- The JMS API specification for message properties is defined in [Message.java](https://github.com/eclipse-ee4j/messaging/blob/master/api/src/main/java/jakarta/jms/Message.java#L1245) which would guide what we put into Message.go
- The underlying Golang MQI layer has a function that looks to allow setting of properties [here](https://github.com/ibm-messaging/mq-golang/blob/95e9b8b09a1fc167747de7d066c49adb86e14dda/ibmmq/mqi.go#L1076) which might be the right basis for the implementation (I've not looked in depth yet)
- There is a page here on [Mapping JMS messages onto IBM MQ messages](https://www.ibm.com/docs/en/ibm-mq/9.2?topic=messages-mapping-jms-onto-mq) that might also be useful reference

**Comment by matrober-uk** [comment]
Will take a look at adding message header property support.

**Comment by matrober-uk** [comment]
Merged support for message properties of type string, int, bool, double under PR #44.
and included in [Release/tag v1.5.0](https://github.com/ibm-messaging/mq-golang-jms20/releases/tag/v1.5.0).
