### ISSUE TITLE
Error calling GetJMSCorrelationID when empty 

### ISSUE THREAD

**Issue by juancgalvis** [ibm-messaging/mq-golang-jms20#40]
When receive a message with empty correlationId the mqmd.CorrelId property value is "000000000000000000000000000000000000000000000000" wich throws this error :

```
panic: runtime error: index out of range [-1] [recovered]
        panic: runtime error: index out of range [-1]

at github.com/ibm-messaging/mq-golang-jms20/mqjms/MessageImpl.go:179 
```

The current code throws error because all bytes are zero and tries to access to correlIDBytes[-1]
```golang
if realLength > 0 {
	for correlIDBytes[realLength-1] == 0 { // error line
		realLength--
	}
}
```

**Comment by matrober-uk** [comment]
Hi @juancgalvis - I just wanted to say that I haven't forgotten this issue/PR - will get to it over the next week or so.
