### ISSUE TITLE
Looking for a new release

### ISSUE THREAD

**Issue by juancgalvis** [ibm-messaging/mq-golang-jms20#42]
Hello @matrober-uk thanks for accepting my contributions, I would like to know when they will be available as a new version in the go packages repository.

Thanks in advance.

**Comment by matrober-uk** [comment]
Hi @juancgalvis - I've created a new release that includes your update along with the other changes since the v1.3.0 release from October last year here;
    https://github.com/ibm-messaging/mq-golang-jms20/releases/tag/v1.4.0

Best regards,

Matt
