### ISSUE TITLE
Receive function of consumer is removing blank spaces at the end of message

### ISSUE THREAD

**Issue by thejams** [ibm-messaging/mq-golang-jms20#45]
Hello, im currently making a produce / consumer application, and everything works fine except that when the consumer receives the message somehow i don't know why the blank spaces at the end of the message send by the producer are gone, somehow the consumer is making some kind of a trim to the message, it is possible for this not to happen ? because i need those blank strings at the end of the message, those belong to the original message and i need them

**Comment by matrober-uk** [comment]
Hi @thejams - I'll take a look at this over the next week too to see if I can resolve the current behaviour.

In the mean time as a (somewhat hacky I admit!) workaround do you have the option to add a non-blank character to the end of the messages when they are sent, and trim that character off when you receive them in your application code - as that approach should honour the blank spaces that exist at the end of the current message text.

**Comment by thejams** [comment]
hi @matrober-uk  thank you very much for the reply, i did a workaround similar to what you mentioned and it works for now, thanks again for the reply dude

**Comment by matrober-uk** [comment]
Fix merged to main under https://github.com/ibm-messaging/mq-golang-jms20/pull/48

Fix included in new tag v1.6.0;
    https://github.com/ibm-messaging/mq-golang-jms20/releases/tag/v1.6.0
