### ISSUE TITLE
Only selectors on JMSCorrelationID are currently supported

### ISSUE THREAD

**Issue by thejams** [ibm-messaging/mq-golang-jms20#46]
is there any posibility to sopport the JMSMessageID selector ? or is there a way to consume a specific message using the message id ?

**Comment by matrober-uk** [comment]
Hi @thejams - it shouldn't be too hard to add support for JMSMessageID selector.  Let me look at that over the next week and I'll post back here with an update.

**Comment by thejams** [comment]
Hi @matrober-uk  great dude !! thank you very much it would be really great

**Comment by matrober-uk** [comment]
Hi @thejams - I've attached a commit in a personal branch that implements the basic behaviour;
    https://github.com/matrober-uk/mq-golang-jms20/tree/getbymsgid

You're welcome to pull that update to try it out locally, and I'll add some additional tests in the near future before merging to main.

**Comment by chughts** [comment]
@thejams remember to update your related GitHub question - https://stackoverflow.com/questions/70970933/only-selectors-on-jmscorrelationid-are-currently-supported

**Comment by matrober-uk** [comment]
Support for get by JMSMessageID merged under https://github.com/ibm-messaging/mq-golang-jms20/pull/47

thanks!

**Comment by matrober-uk** [comment]
Fix included in new tag v1.6.0;
    https://github.com/ibm-messaging/mq-golang-jms20/releases/tag/v1.6.0
