### ISSUE TITLE
Link for Linux toolkit broken

### ISSUE THREAD

**Issue by Aornn** [ibm-messaging/mq-golang-jms20#5]
Hi !
I'm desperately looking for the linux toolkit the old link in the readme was this one : https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.1.1.0-IBM-MQC-Redist-LinuxX64.tar.gz

But it's broken and i didn't find any others links.
I will be happy if you can link me another toolkit :)

Thanks !

**Comment by Aornn** [comment]
No one ....?

**Comment by matrober-uk** [comment]
Hi @Aornn - if you trim the filename off the end of that URL and get the directory listing there are a number of other more up to date versions of that file;

https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/

For example the latest 9.1.5 is available here; https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.1.5.0-IBM-MQC-Redist-LinuxX64.tar.gz

**Comment by matrober-uk** [comment]
sorry, I didn't see your issue the first time round for some reason!

**Comment by Aornn** [comment]
Ho thanks ! No problem, i understand it's not really easy those days.

**Comment by matrober-uk** [comment]
I'll update the readme links as well.
