### ISSUE TITLE
Not working example openshift-app-sample for docker

### ISSUE THREAD

**Issue by ChipArtem** [ibm-messaging/mq-golang-jms20#59]
[openshift-app-sample](https://github.com/ibm-messaging/mq-golang-jms20/tree/main/openshift-app-sample) cannot be used. 
Due to the missing file 9.2.0.*-IBM-MQC-Redist-LinuxX64.tar.gz in [site](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/).

Due to absence of file at path, it is created empty. Image creation is interrupted on unpacking

 => ERROR [builder 3/7] RUN cd /opt/mqm    && curl -LO "https://public.dhe.ibm.com/ibmdl/export/pub/so  1.0s
 => [stage-1 3/5] WORKDIR /go/src/openshift-app-sample                                                  0.0s
------
 > [builder 3/7] RUN cd /opt/mqm    && curl -LO "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.2.0.1-IBM-MQC-Redist-LinuxX64.tar.gz"    && tar -zxf ./*.tar.gz    && rm -f ./*.tar.gz    && bin/genmqpkg.sh -b /opt/mqm:
#8 0.176   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#8 0.176                                  Dload  Upload   Total   Spent    Left  Speed
100   196  100   196    0     0    261      0 --:--:-- --:--:-- --:--:--   261
#8 0.940 
#8 0.940 gzip: stdin: not in gzip format
#8 0.941 tar: Child returned status 1
#8 0.941 tar: Error is not recoverable: exiting now

**Comment by matrober-uk** [comment]
thanks @ChipArtem - as you say, it looks like the 9.2.0.1 image has been cycled out of that download site.
I'll look at updating the Dockerfile to pick a newer image.

For reference if you hadn't seen it and want to work around it locally, that definition is controlled here;
https://github.com/ibm-messaging/mq-golang-jms20/blob/main/openshift-app-sample/Dockerfile#L8

**Comment by matrober-uk** [comment]
Updated Dockerfile to MQ 9.3.0.0, which will be retained on the download server much longer.
