### ISSUE TITLE
Possible connection/context leak in `CreateContextWithSessionMode`

### ISSUE THREAD

**Issue by manheckxx** [ibm-messaging/mq-golang-jms20#72]
Greetings,

we use your library in our project for communicating with queue managers and are currently experiencing some issues with error code [2391 (`MQRC_SSL_ALREADY_INITIALIZED`)](https://www.ibm.com/docs/en/ibm-mq/9.4?topic=codes-2391-0957-rc2391-mqrc-ssl-already-initialized).

We have logic to attempt a reconnect when encountering certain errors and noticed that while we tried to close the connections, the connections still seemed to pile up.

I think this might be due to the way non-OK return codes are handled by this library.

As I understand, code 2391 signifies that a connection has successfully been established, albeit ignoring the provided SSL/TLS settings, re-using the configuration of an existing connection instead.

Looking at the upstream library, `mq-golang`, shows that

https://github.com/ibm-messaging/mq-golang/blob/2a31ece25fbfa7a78a1bb49ce4968a6eda35e68d/ibmmq/mqi.go#L259-L262

seems to possibly return both a connection and an error on a non-OK return code, but here in `mq-golang-jms20`

https://github.com/ibm-messaging/mq-golang-jms20/blob/b349e7619e5e44c04f9fac342b399edd49761860/mqjms/ConnectionFactoryImpl.go#L147-L177

a connection context is only returned if the return code says no errors occurred.

In my opinion, this prevents both using or closing the connection, causing a connection leak in this case.

Any thoughts on this?

**Comment by matrober-uk** [comment]
Hi @manheckxx - thanks for raising this issue, and for investigating the code behaviour that caused it  👍 

I've made the necessary code update, and validated with a new testcase that reproduces the scenario you described under #73, which is now also packaged as [release v1.13.0](https://github.com/ibm-messaging/mq-golang-jms20/releases/tag/v1.13.0) of this library.

Please feel free to re-open this issue if you find the fix doesn't work for you.
Regards, Matt.
