### ISSUE TITLE
Buffer Length

### ISSUE THREAD

**Issue by ethanrucinski** [ibm-messaging/mq-golang-jms20#9]
Would you consider adding the buffer length as something you can configure? I had to redo some code on my own project since I had to introduce a longer buffer. 

I'm happy to try to contribute something like that if you like. 

Please don't roast me if my buffer is too big now... I just added a 1 in front of your number. 

-Ethan

**Comment by matrober-uk** [comment]
Hi @ethanrucinski - welcome, and thanks for your engagement!

Making the buffer length configurable sounds like a very reasonable suggestion - are you thinking specifically of the buffer when receiving a message, for example at https://github.com/ibm-messaging/mq-golang-jms20/blob/f9167718c28b954748a38783625cad56322a7b66/mqjms/ConsumerImpl.go#L63?

If you're willing to contribute a proposal that sounds great - please note the guidelines under [Contributing](https://github.com/ibm-messaging/mq-golang-jms20#contributing), in particular the final sentence about needing to confirm your agreement to the CLA.

I would suggest that we want to find a way that users continue to get the current value by default, but have the option to override that by making an explicit call to update the buffer length that will be used - for example perhaps adding a new signature onto the [JMSConsumer.go](https://github.com/ibm-messaging/mq-golang-jms20/blob/f9167718c28b954748a38783625cad56322a7b66/jms20subset/JMSConsumer.go) interface along the lines of "setBufferSize" or similar?

**Comment by matrober-uk** [comment]
I'm going to pick this one up to close it out.

I'm going to make the buffer size configurable with a setting on the ConnectionFactory so that it can be controlled administratively rather than having to enforce it in code.

**Comment by matrober-uk** [comment]
Hi @ethanrucinski - I've merged the change to make the receive buffer configurable by setting a property on the ConnectionFactory before you create your connection/context object, example is shown in the associated testcase as follows (note that you can set the value to a large constant up front, you don't have to go through the pattern shown in the testcase) 
https://github.com/ibm-messaging/mq-golang-jms20/blob/master/largemessage_test.go#L66

Hope that helps in the future!

**Comment by ethanrucinski** [comment]
Thanks Matt! Sorry I never closed this out... wound up switching to using NodeJS

**Comment by matrober-uk** [comment]
ah, ok - sorry to hear that - maybe Golang next time around!

**Comment by ethanrucinski** [comment]
I liked it; it was fast... but not enough support on my team :(
